# Generated by Django 4.1 on 2022-09-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autores', '0002_alter_autor_fotoperfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='sombreMi',
            new_name='sobreMi',
        ),
    ]
