# Generated by Django 4.1 on 2022-09-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='image/post/')),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(max_length=300)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autores.autor')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.tematica')),
            ],
        ),
    ]
